apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  selector:
    app: portal-noticias
  type: NodePort
  ports:
  - port: 80
    # targetPort: <Target Port>
    nodePort: 30000
