apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    name: db-sistema-noticias
spec:
  containers:
  - name: conteiner-db-sistema-noticia
    image: aluracursos/mysql-db:1
    resources:
    # limits:
    #   memory: "128Mi"
    #   cpu: "500m"
    ports:
    - containerPort: 3306
    envFrom:
    - configMapRef:
        name: db-configmap

