apiVersion: v1
kind: Pod
metadata:
  name: pod-sistema-noticias
  labels:
    app: sistemas-noticias
spec:
  containers:
  - name: conteiner-sistema-noticia
    image: aluracursos/sistema-noticias:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: sistema-configmap
