apiVersion: v1
kind: Pod
metadata:
  name: pod-primeiro-volume
  labels:
    name: primeiro-volume
spec:
  containers:
  - name: nginx-conteiner
    image: nginx:latest
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    volumeMounts:
    - mountPath: /volume-dentro-do-conteiner
      name: primeiro-volume
  - name: jenkins-conteiner
    image: jenkins/jenkins:lts
    resources:
      limits:
        memory: "1Gi"
        cpu: "1"
      requests:
        memory: "512Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /volume-dentro-do-conteiner
      name: primeiro-volume
  volumes:
  - name: primeiro-volume
    hostPath:
      path: /f/Codificação/alura/kubernetes/primeiro-volume
      type: Directory
