apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-noticias
  template:
    metadata:
      labels:
        app: db-noticias
    spec:
      containers:
      - name: conteiner-db-sistema-noticia
        image: aluracursos/mysql-db:1
        resources:
        # limits:
        #   memory: "128Mi"
        #   cpu: "500m"
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: db-configmap
